import { Button, VerticalBox } from "std-widgets.slint";

component CButton inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #456;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
    }
    touch := TouchArea { }
}

export component AppWindow inherits Window {

    title: "Counter";
    min-width: 270px;
    min-height: 100px;

    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
    
    
        Text {
            text: "Counter: \{root.counter}";
            
        }

        CButton {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
                debug(counter)
            }
        }
    }
}

